<?php
/**
 * @Author yaangvu
 * @Date   Jul 26, 2021
 */

namespace YaangVu\LaravelBase\Services;


use Illuminate\Database\Eloquent\Model;
use YaangVu\LaravelBase\Models\Example;

class ExampleService extends BaseService
{

    public function initModel(): void
    {
        $this->model = new Example();
    }

    public function update(int|string $id, object $request, bool $transaction = false): Model
    {
        $request->abc = 123;

        return parent::update($id, $request, $transaction); // TODO: Change the autogenerated stub
    }
}