<?php

namespace YaangVu\LaravelBase\Generator\Console;

use Illuminate\Console\GeneratorCommand;
use Illuminate\Foundation\Console\ExceptionMakeCommand as ConsoleExceptionMakeCommand;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Input\InputOption;
use YaangVu\LaravelBase\Generator\GeneratorHelper;
use Illuminate\Support\Str;

#[AsCommand(name: 'yaangvu:base:exception')]
class ExceptionMakeCommand extends ConsoleExceptionMakeCommand
{
    use GeneratorHelper;
    /**
     * The console command name.
     *
     * @var string
     */
    protected $name = 'yaangvu:base:exception';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a new custom exception class';

    /**
     * The type of class being generated.
     *
     * @var string
     */
    protected $type = 'Exception';

    /**
     * Get the stub file for the generator.
     *
     * @return string
     */
    public function handle()
    {
        $this->setup();
        return parent::handle(); // TODO: Change the autogenerated stub
    }
    /**
     * Determine if the class already exists.
     *
     * @param  string  $rawName
     * @return bool
     */
  
    protected function getPath($name): string
    {
        $path = $this->rootNamespace() . '\\'
            . Str::pluralStudly($this->type) . '\\'
            . $this->arrName['last'];
        $path = str_replace('\\', '/', $path);

        return $this->laravel->basePath($path)
            . ($this->type === 'Model' ? '' : $this->type)
            . '.php';
    }
}
