<?php

namespace YaangVu\LaravelBase\Generator\Console;

use Illuminate\Console\GeneratorCommand;
use Illuminate\Foundation\Console\RequestMakeCommand as ConsoleRequestMakeCommand;
use Symfony\Component\Console\Attribute\AsCommand;

use YaangVu\LaravelBase\Generator\GeneratorHelper;
use Illuminate\Support\Str;
#[AsCommand(name: 'yaangvu:base:request')]
class RequestMakeCommand extends ConsoleRequestMakeCommand
{
    use GeneratorHelper;
    /**
     * The console command name.
     *
     * @var string
     */
    protected $name = 'yaangvu:base:request';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a new form request class';

    /**
     * The type of class being generated.
     *
     * @var string
     */
    protected $type = 'Request';

    protected function getDefaultNamespace($rootNamespace)
    {
        return $rootNamespace.'\Requests';
    }

    protected function getPath($name): string
    {
        $path = $this->rootNamespace() . '\\'
            . Str::pluralStudly($this->type) . '\\'
            . $this->arrName['last'];
        $path = str_replace('\\', '/', $path);

        return $this->laravel->basePath($path)
            . ($this->type === 'Model' ? '' : $this->type)
            . '.php';
    }
    
    public function handle()
    {
        $this->setup();
        return parent::handle(); // TODO: Change the autogenerated stub
    }


}
