<?php

namespace YaangVu\LaravelBase\Generator\Console;

use Illuminate\Console\Concerns\CreatesMatchingTest;
use Illuminate\Support\Str;
use Symfony\Component\Console\Attribute\AsCommand;
use YaangVu\LaravelBase\Generator\GeneratorHelper;

#[AsCommand(name: 'yaangvu:base:resource')]
class ResourceMakeCommand extends \Illuminate\Foundation\Console\ResourceMakeCommand
{
    use CreatesMatchingTest, GeneratorHelper;

    /**
     * The console command name.
     *
     * @var string
     */
    protected $name = 'yaangvu:base:resource';
    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a new resource class';
    /**
     * The type of class being generated.
     *
     * @var string
     */
    protected $type = 'Resource';


    public function handle()
    {
        $this->setup();
        parent::handle(); // TODO: Change the autogenerated stub
    }


    protected function getPath($name): string
    {
        $path = $this->rootNamespace() . '\\'
            . Str::pluralStudly($this->type) . '\\'
            . $this->arrName['last'];
        $path = str_replace('\\', '/', $path);

        // dd($path);
        return $this->laravel->basePath($path) . 'Resource.php';
    }

    protected function qualifyClass($name)
    {
        return $this->getDefaultNamespace($this->rootNamespace()) . "\\" . $name . 'Resource';
    }

}