<?php
/**
 * @Author yaangvu
 * @Date   Jul 26, 2021
 */

namespace YaangVu\LaravelBase\Docs\Example;


use Illuminate\Database\Eloquent\Model;
use YaangVu\LaravelBase\Services\BaseService;

class ExampleService extends BaseService
{

    public function initModel(): void
    {
        $this->model = new Example();
    }

    public function update(int|string $id, object $request, bool $transaction = false): Model
    {
        $this->mergeRequestParams($request, ['additional_param' => 'Hello world']);

        return parent::update($id, $request, $transaction); // TODO: Change the autogenerated stub
    }
}